apiVersion: v1
kind: ConfigMap
metadata:
  name: cardano-node-topology
data:
  topology.json: |
    {
      "Producers":
        [
          {
            "addr": "relays-new.staging-shelley.dev.iohkdev.io",
            "port": 3001,
            "valency": 1
          }
        ]
    }
