---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db
data:
  postgres_db: {{ .Values.postgres.db | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user
data:
  postgres_user: {{ .Values.postgres.user | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
data:
  postgres_password: {{ .Values.postgres.password | b64enc }}
  